export {default as ConfirmEventDialog} from './_confirmEventDialog'
export {default as EmployeeDeleteDialog} from './_employeeDeleteDialog'
export {default as EmployeeEditDialog} from './_employeeEditDialog'
export {default as EmployeeRegisterDialog} from './_employeeRegisterDialog'
export {default as EmployeeTripsDialog} from './_employeeTripsDialog'
